<?php

class Shop
{
    private $name;
    private $price;

    protected function __construct($name2,$price2)
    {
        $this->name = $name2;
        $this->price = $price2;
    }

    protected function showInfo()
    {
        $str = "商品名称：{$this->name}";
        $str .= "<br />商品价格：{$this->price}";
        return $str;

    }
}


class Mobile extends Shop
{
    private $pinpai;
    private $city;

    public function __construct($name2, $price2,$pinpai2,$city2)
    {
        parent::__construct($name2, $price2);
        $this->pinpai = $pinpai2;
        $this->city   = $city2;
    }

    //重写父类的showInfo()方法
    public function showInfo()
    {
        $srt = parent::showInfo(); // TODO: Change the autogenerated stub
        $srt .="<br />手机品牌：{$this->pinpai}";
        $srt .="<br />手机产地：{$this->city}";
        return $srt;
    }


}


class Book extends Shop
{
    private $author;
    private $publish;

    public function __construct($name2, $price2,$author2,$publish2)
    {
        parent::__construct($name2, $price2);
        $this->author = $author2;
        $this->publish   = $publish2;
    }

    //重写父类的showInfo()方法
    public function showInfo()
    {
        $srt = parent::showInfo(); // TODO: Change the autogenerated stub
        $srt .="<br />书作者：{$this->author}";
        $srt .="<br />出版社：{$this->publish}";
        return $srt;
    }


}

//创建Moblie的对象
$obj1 = new Mobile("苹果X",8888,"苹果","天津");
echo $obj1->showInfo();
echo "<hr />";
$obj2 = new Book("从入门到放弃","50","佳明","南昌");
echo $obj2->showInfo();